/* GENERATED by milan-linux/tools/gen-nvm-shape.py from endstation_ax7101_1x1_tdm8.yaml at milan-fpga 17f62ef64a66562384e8a93b1d6be6f86e51f95c,
 * through sw/firmware/ctrl_nvm/test/nvm_bench.py shape_header. DO NOT EDIT: regenerate.
 * The identity words are milan-ctrld's run-time variables (src/nvm_file.c). */
#ifndef NVM_SHAPE_GEN_H
#define NVM_SHAPE_GEN_H
#include <stdint.h>
extern uint32_t milan_nvm_entity_id_lo, milan_nvm_entity_id_hi;
extern uint32_t milan_nvm_model_id_lo, milan_nvm_model_id_hi;
#define MILAN_ENTITY_ID_LO milan_nvm_entity_id_lo
#define MILAN_ENTITY_ID_HI milan_nvm_entity_id_hi
#define MILAN_MODEL_ID_LO milan_nvm_model_id_lo
#define MILAN_MODEL_ID_HI milan_nvm_model_id_hi
#define MILAN_NVM_SHAPE_MODEL_ID_LO 0x935893e1u
#define MILAN_NVM_SHAPE_MODEL_ID_HI 0x1bc5c1u
#define MILAN_NVM_N_STREAM_IN 0x2u
#define MILAN_NVM_N_STREAM_OUT 0x2u
#define MILAN_NVM_N_SPORT_IN 0x1u
#define MILAN_NVM_N_SPORT_OUT 0x1u
#define MILAN_NVM_N_AUDIO_UNIT 0x1u
#define MILAN_NVM_N_CLK_DOM 0x1u
#define MILAN_NVM_N_NAME 0x27u
#define MILAN_NVM_BIND_BASE 0x20u
#define MILAN_NVM_REC_LAYOUT 0x2u
#define MILAN_NVM_MAPIN_ENTRIES_0 0x8u
#define MILAN_NVM_MAPIN_ENTRIES_1 0x0u
#define MILAN_NVM_MAPIN_ENTRIES_2 0x0u
#define MILAN_NVM_MAPIN_ENTRIES_3 0x0u
#define MILAN_NVM_MAPIN_ENTRIES_4 0x0u
#define MILAN_NVM_MAPIN_ENTRIES_5 0x0u
#define MILAN_NVM_MAPIN_ENTRIES_6 0x0u
#define MILAN_NVM_MAPIN_ENTRIES_7 0x0u
#define MILAN_NVM_MAPIN_ENTRIES_8 0x0u
#define MILAN_NVM_MAPIN_ENTRIES_9 0x0u
#define MILAN_NVM_MAPIN_ENTRIES_10 0x0u
#define MILAN_NVM_MAPIN_ENTRIES_11 0x0u
#define MILAN_NVM_MAPIN_ENTRIES_12 0x0u
#define MILAN_NVM_MAPIN_ENTRIES_13 0x0u
#define MILAN_NVM_MAPIN_ENTRIES_14 0x0u
#define MILAN_NVM_MAPIN_ENTRIES_15 0x0u
#define MILAN_NVM_MAPOUT_ENTRIES_0 0x11u
#define MILAN_NVM_MAPOUT_ENTRIES_1 0x0u
#define MILAN_NVM_MAPOUT_ENTRIES_2 0x0u
#define MILAN_NVM_MAPOUT_ENTRIES_3 0x0u
#define MILAN_NVM_MAPOUT_ENTRIES_4 0x0u
#define MILAN_NVM_MAPOUT_ENTRIES_5 0x0u
#define MILAN_NVM_MAPOUT_ENTRIES_6 0x0u
#define MILAN_NVM_MAPOUT_ENTRIES_7 0x0u
#define MILAN_NVM_MAPOUT_ENTRIES_8 0x0u
#define MILAN_NVM_MAPOUT_ENTRIES_9 0x0u
#define MILAN_NVM_MAPOUT_ENTRIES_10 0x0u
#define MILAN_NVM_MAPOUT_ENTRIES_11 0x0u
#define MILAN_NVM_MAPOUT_ENTRIES_12 0x0u
#define MILAN_NVM_MAPOUT_ENTRIES_13 0x0u
#define MILAN_NVM_MAPOUT_ENTRIES_14 0x0u
#define MILAN_NVM_MAPOUT_ENTRIES_15 0x0u
#define MILAN_NVM_HEARTBEAT_MS 0xfau
#define MILAN_NVM_DEBOUNCE_MS 0x3e8u
#define MILAN_NVM_ERASE_TIMEOUT_MS 0xdacu
#define MILAN_NVM_PROGRAM_TIMEOUT_MS 0x32u
#define MILAN_NVM_RESTORE_TIMEOUT_MS 0xbb8u
#define MILAN_FLASH_JOURNAL_OFFSET 0xee0000u
#define MILAN_FLASH_JOURNAL_SIZE 0x20000u
#endif
