#!/bin/sh

# SPDX-FileCopyrightText: Copyright (c) 2026 Kebag-Logic
# SPDX-License-Identifier: MIT

# Let U-Boot's vendored pylibfdt build against SWIG >= 4.3.
#
# U-Boot assembles tiboot3.bin / tispl.bin with binman, a Python tool that
# rewrites device trees, so it needs the libfdt Python bindings:
#
#   CONFIG_BINMAN -> select DTOC -> select PYLIBFDT   (dts/Kconfig)
#     -> scripts/dtc/Makefile: subdir-$(CONFIG_PYLIBFDT) += pylibfdt
#       -> setup.py build_ext, SWIG_OPTS=...
#         -> swig generates libfdt_wrap.c from libfdt.i
#
# scripts/dtc/pylibfdt/libfdt.i_shipped still writes two typemaps with the
# Python 2 spellings PyInt_AsLong() and PyString_FromString(). Those compiled
# under Python 3 only because SWIG's own runtime header defined them away.
# SWIG 4.3 removed that Python 2 compatibility layer, so on a host with a
# current swig (Arch ships 4.5.x) the build dies with:
#
#   libfdt_wrap.c: error: implicit declaration of function 'PyInt_AsLong'
#   libfdt_wrap.c: error: implicit declaration of function 'PyString_FromString'
#
# Using the distro dtc instead (DTC=/usr/bin/dtc, which makes U-Boot assume a
# system pylibfdt) is NOT a way out: U-Boot passes -Wno-graph_child_address,
# a check name upstream dtc 1.8.x does not have, so the DTB rules then fail
# with 'Unrecognized check name "graph_child_address"'. U-Boot needs its own
# dtc, so its own pylibfdt has to build.
#
# Idempotent, and a no-op on an older swig that still supplies the macros
# (the inserted defines are #ifndef-guarded).
#
# Usage: fix-pylibfdt-swig.sh [<u-boot-src>]   (default: ../../u-boot-official)
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
UB=${1:-$(cd "$HERE/../.." && pwd)/u-boot-official}
I="$UB/scripts/dtc/pylibfdt/libfdt.i_shipped"
MARKER='SWIG 4.3 dropped'

[ -f "$UB/Makefile" ] || { echo "not a U-Boot tree: $UB" >&2; exit 1; }
[ -f "$I" ] || { echo "no $I - nothing to fix" >&2; exit 0; }

if grep -q "$MARKER" "$I"; then
	echo "pylibfdt: SWIG >= 4.3 fix already present"
	exit 0
fi

python3 - "$I" <<'PY'
import sys
p = sys.argv[1]
s = open(p).read()
old = '''%{
#define SWIG_FILE_WITH_INIT
#include "libfdt.h"
'''
new = '''%{
#define SWIG_FILE_WITH_INIT
#include "libfdt.h"

/*
 * The typemaps below use the Python 2 spellings PyInt_AsLong() and
 * PyString_FromString().  Those used to compile under Python 3 only because
 * SWIG's own runtime header defined them away; SWIG 4.3 dropped that Python 2
 * compatibility layer, so the generated wrapper stopped building (implicit
 * declaration of 'PyInt_AsLong' / 'PyString_FromString').  Define them here.
 * Guarded with #ifndef so an older SWIG that still supplies them is untouched.
 */
#if PY_VERSION_HEX >= 0x03000000
#ifndef PyInt_AsLong
#define PyInt_AsLong(x)\t\tPyLong_AsLong(x)
#endif
#ifndef PyString_FromString
#define PyString_FromString(x)\tPyUnicode_FromString(x)
#endif
#endif
'''
if s.count(old) != 1:
    sys.exit("libfdt.i_shipped does not look like the expected file; "
             "check whether U-Boot has fixed this upstream and drop this script")
open(p, "w").write(s.replace(old, new))
PY

# a wrapper generated by the previous, failing run would otherwise be reused
rm -f "$UB"/out_*/*/scripts/dtc/pylibfdt/libfdt.i \
      "$UB"/out_*/*/scripts/dtc/pylibfdt/libfdt_wrap.c \
      "$UB"/out_*/*/scripts/dtc/pylibfdt/libfdt.py \
      "$UB"/out_*/*/scripts/dtc/pylibfdt/_libfdt*.so 2>/dev/null || true

echo "pylibfdt: patched $I for SWIG >= 4.3"
