#!/bin/sh

# SPDX-FileCopyrightText: Copyright (c) 2026 Kebag-Logic
# SPDX-License-Identifier: Apache-2.0

# Generate milan-ctrld's entity.conf from an end-station config, through
# milan-fpga's own adp_entity.py, so the ADP fields are the builder's
# derivation and never a restated copy. The YAML's entity_id and mac are
# dropped: on the PocketBeagle 2 both come from the interface's MAC at run time
# (the builder's "mac-derived" rule, applied by milan-ctrld).
#
# The milan-fpga tree needs its protocol-processor and gptp-processor
# submodules (tools/fetch-milan-fpga.sh --with-submodules).
#
# usage: gen-entity-conf.sh <milan-fpga tree> <end-station yaml> > entity.conf

set -e
TREE=${1:?usage: gen-entity-conf.sh <milan-fpga tree> <end-station yaml>}
YAML=${2:?usage: gen-entity-conf.sh <milan-fpga tree> <end-station yaml>}
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

python3 "$TREE/sw/firmware/ctrl/adp/adp_entity.py" "$YAML" -o "$TMP" >&2
REV=$(cat "$TREE/.milan-fpga-rev" 2>/dev/null || echo unknown)

echo "# milan-ctrld entity description: the struct adp_entity fields (adp.h)"
echo "# GENERATED by milan-linux/tools/gen-entity-conf.sh from"
echo "#   $(basename "$YAML") at milan-fpga $REV, through sw/firmware/ctrl/adp/adp_entity.py."
echo "# DO NOT EDIT: regenerate. entity_id and mac come from the interface at run time."
sed -n 's/^[[:space:]]*\.\([a-z_]*\) = \(0x[0-9A-Fa-f]*\)u*l*l*,* *\\*$/\1=\2/p' "$TMP" |
	grep -v -e '^entity_id=' -e '^mac='
