#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 Kebag-Logic
# SPDX-License-Identifier: Apache-2.0
"""gen-nvm-shape.py - nvm_shape_gen.h for the saved-state store on Linux (#13).

The Mark II store (milan-fpga sw/firmware/ctrl_nvm) is compiled against the
shape constants of one end-station config: its record set, its binding layout
and the journal's place. milan-fpga's own host suite derives them
(sw/firmware/ctrl_nvm/test/nvm_bench.py shape_header, through the builder), and
this runs that derivation, never a restated copy. One change: on the
PocketBeagle 2 the entity and model IDs are known only at run time (the
entity ID is eth0's MAC, expanded), so the four identity words become
variables milan-ctrld sets before the store boots. The model ID the shape was
derived for stays a constant, MILAN_NVM_SHAPE_MODEL_ID_LO/HI: milan-ctrld takes
the model as proven only when the entity advertises that one.

usage: gen-nvm-shape.py <milan-fpga tree> <end-station yaml> > nvm_shape_gen.h
"""

import re
import sys
import tempfile
from pathlib import Path


def main() -> int:
    tree, cfg = Path(sys.argv[1]).resolve(), Path(sys.argv[2]).resolve()
    sys.path.insert(0, str(tree / "sw/firmware/ctrl_nvm/test"))
    import nvm_bench as nb  # noqa: E402
    with tempfile.TemporaryDirectory() as work:
        inputs = nb.shape_inputs(cfg, Path(work))
        header = nb.shape_header(inputs.shape, inputs.donor, inputs.ident)
    model = inputs.ident.model_id
    rev = (tree / ".milan-fpga-rev").read_text().strip() if (tree / ".milan-fpga-rev").exists() else "unknown"
    out = [f"/* GENERATED by milan-linux/tools/gen-nvm-shape.py from {cfg.name} at milan-fpga {rev},",
           " * through sw/firmware/ctrl_nvm/test/nvm_bench.py shape_header. DO NOT EDIT: regenerate.",
           " * The identity words are milan-ctrld's run-time variables (src/nvm_file.c). */"]
    for line in header.splitlines():
        if line.startswith("/*"):
            continue
        m = re.match(r"#define (MILAN_(?:ENTITY|MODEL)_ID_(?:LO|HI)) ", line)
        if m:
            continue
        out.append(line)
        if line == "#define NVM_SHAPE_GEN_H":
            out += ["#include <stdint.h>",
                    "extern uint32_t milan_nvm_entity_id_lo, milan_nvm_entity_id_hi;",
                    "extern uint32_t milan_nvm_model_id_lo, milan_nvm_model_id_hi;",
                    "#define MILAN_ENTITY_ID_LO milan_nvm_entity_id_lo",
                    "#define MILAN_ENTITY_ID_HI milan_nvm_entity_id_hi",
                    "#define MILAN_MODEL_ID_LO milan_nvm_model_id_lo",
                    "#define MILAN_MODEL_ID_HI milan_nvm_model_id_hi",
                    f"#define MILAN_NVM_SHAPE_MODEL_ID_LO 0x{model & 0xFFFF_FFFF:x}u",
                    f"#define MILAN_NVM_SHAPE_MODEL_ID_HI 0x{model >> 32:x}u"]
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
