# RAUC A/B config — bootnames match the U-Boot bootchooser BOOT_ORDER="A B"
[system]
compatible=myir-am62x
bootloader=uboot
statusfile=per-slot

[keyring]
path=/etc/rauc/keyring.pem

[slot.rootfs.0]
device=/dev/mmcblk1p2
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/mmcblk1p3
type=ext4
bootname=B
